### ISSUE TITLE
很好的翻译！

### ISSUE THREAD

**Issue by doyou** [xiaoweiChen/CPP-20-STL-Cookbook#2]
从CPP-17-STL-Cookbook来的，很好的翻译！
PDF目录工作不太正常（TOC链接无误）。

搜索一番，终于找到原译者，并且现在有CPP-20-STL-Cookbook，PDF目录也正常了！
还没细看，发现有个地方多了个空格导致打开链接有点小问题。

第28行 @ /content/preface.tex

> 本书假定读者对C++有基本的了解，包括语法、结构、数据类型、类和对象、模板和STL。
本书中例子假定已经包含某些头文件来使用库函数。示例通常不会列出所有必要的头文件，而更倾向于关注当前描述的技术。建议读者下载示例代码，其中包含完整的代码段。
可以从GitHub下载示例代码: \url{https://**github.com/ PacktPublishing**/CPP-20-STL-Cookbook}。

**Comment by xiaoweiChen** [comment]
首先感谢勘误！

要是阅读的时候发现有超链接地址的问题，可以fork这个库，对相应的问题进行修改，然后给这个库提PR。PR接收后，我会重新生成pdf，并将其放在Release页面中。

**Comment by xiaoweiChen** [comment]
感谢对《C++17 STL Cook book》译版的认可。

这本使用的markdown来做的，当时使用gitbook生成的PDF，所以目录跳转会有问题。

现在，都是使用Latex直接来做译版，所以目录跳转应该没有问题了。
